spring:
  application:
    name: tourist-management-app
  datasource:
    url: jdbc:sqlserver://yuva-fse-sql-server.database.windows.net:1433;database=yuvafsedb;user=azureuser@yuva-fse-sql-server;password=Pa$$w0rD-Yuva-F$E;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: azureuser
    password: Pa$$w0rD-Yuva-F$E
  # Hibernate settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
  jms:
    servicebus:
      connection-string: Endpoint=sb://yuva-fse-service-bus-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=DRhwlHiX2uTqIx/PlJBcTxvr9WmaKv+2j+ASbCy44HE=
      pricing-tier: basic
logging:
  level:
    root: INFO
    com.cognizant.fse.assignment: DEBUG
    org.hibernate.SQL: DEBUG
