spring:
  application:
    name: tourist-management-app
  datasource:
    url: ${DATABASE_URL}
    username: azureuser
    password: Pa$$w0rD-Yuva-F$E
  # Hibernate settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
  jms:
    servicebus:
      connection-string: ${SERVICE_BUS_CONNECTION_STRING}
      pricing-tier: basic
logging:
  level:
    root: INFO
    com.cognizant.fse.assignment: DEBUG
    org.hibernate.SQL: DEBUG
